account/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .auth import (
    signup,
    validate_passcode,
    set_passcode,
    login_view,
    logout_view,
)
from .generate import (
    password_generator,
    generated_password,
    strong_password
)
from .update import (
    update_profile,
    change_password,
    update_passcode
)
from .views import (
    landing,
    dashboard,
    about,
    privacy,
    contact_us,
    help_page
)


app_name = 'auth'

urlpatterns = [
    # auth.py module path (views routes)
    path(
        'signup/', signup, name='signup'),
    path(
        'login/', login_view, name='login'),
    path(
        'validate/passcode/?next=/<str:next_url>/', validate_passcode, name='validate_passcode'),
    path(
        'logout/', logout_view, name='logout'),
    path(
        'set/passcode/', set_passcode, name='set_passcode'),
        

    # generator.py module path (views routes)
    path(
        'password/generator/', password_generator, name='password_generator'),
    path(
        'generated/password/', generated_password, name='generated_password'),
    path(
        'strong/password/<int:pwd_id>/', strong_password, name='strong_password'),
        

    # update.py module path (views routes)
    path(
        'update/profile/', update_profile, name='update_profile'),
    path(
        'change/password/', change_password, name='change_password'),
    path(
        'update/passcode/', update_passcode, name='update_passcode'),
        

    # views.py module path (views routes)
    path(
        '', landing, name='landing'),
    path(
        'dashboard/', dashboard, name='dashboard'),
    path(
        'about/', about, name='about'),
    path(
        'privacy/', privacy, name='privacy'),
    path(
        'contact/us/', contact_us, name='contact_us'),
    path(
        'help/', help_page, name='help'),
]

encme/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('secureapp.urls')),
]

passaccess/urls.py
from django.contrib import admin
from django.urls import path, include


# There are 4 already defined handler methods in `django.urls` functions.
handler400 = 'account.views.error_400'
handler403 = 'account.views.error_403'
handler404 = 'account.views.error_404'
handler500 = 'account.views.error_500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('secureapp.urls')),
]

secureapp/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .update import (
    update_item,
    update_item_salt
)
from .views import (
    new_item,
    new_item_fields,
    item_info,
    search_trusted_user,
    add_trusted_user,
    remove_trusted_user,
    remove_all_trusted_user,
    delete_item,
)


app_name = 'secureapp'

urlpatterns = [
    # views.py module path (views routes)
    path(
        'update/item/<int:item_id>/', update_item, name='update_item'),
    path(
        'update/item/salt/<int:item_id>/', update_item_salt, name='update_item_salt'),


    # views.py module path (views routes)
    path(
        'new/item/', new_item, name='new_item'),
    path(
        'new/item/fields', new_item_fields, name='new_item_fields'),
    path(
        'item/info/<int:item_id>/', item_info, name='item_info'),
    path(
        'search/trusted/<int:item_id>/', search_trusted_user, name='search_trusted_user'),
    path(
        'add/trusted/<int:item_id>/<int:user_id>/', add_trusted_user, name='add_trusted_user'),
    path(
        'remove/trusted/<int:item_id>/<int:user_id>/', remove_trusted_user, name='remove_trusted_user'),
    path(
        'remove/all/trusted/<int:item_id>/', remove_all_trusted_user, name='remove_all_trusted_user'),
    path(
        'delete/item/<int:item_id>/', delete_item, name='delete_item'),
]

secureapp/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth import get_user_model
from .models import SecureItemInfo


User = get_user_model()


class SecureItemInfoForm_1(forms.ModelForm):
    category = forms.CharField(required=True)
    platform = forms.CharField(required=True)
    visibility = forms.CharField(required=True)

    i_label = forms.CharField(required=True)
    selected_category = forms.CharField(required=True)
    selected_platform = forms.CharField(required=True)

    class Meta:
        model = SecureItemInfo
        fields = ['category', 'platform', 'custom_platform', 'visibility', 'i_label']
        
        
class SecureItemInfoForm_2(forms.ModelForm):
    i_label = forms.CharField(required=True)
    category = forms.CharField(required=True)
    visibility = forms.CharField(required=True)
    platform = forms.CharField(required=True)
    
    class Meta:
        model = SecureItemInfo
        fields = ['the_key', 'custom_platform', 'i_username', 'i_phone', 'i_email', 'i_password', 'i_passphrase', 'i_api', 'i_ssh_key_pub', 'i_ssh_key_prt', 'i_card_no', 'i_card_valid_range', 'i_card_ccv', 'i_card_pin']

secureapp/views.py
# -*- coding: utf-8 -*-
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone
from django.core.paginator import Paginator
from django.shortcuts import (
    render,
    redirect
)
from django.contrib.auth import get_user_model
from django.contrib import messages as flash_msg
from .models import (
    Platform,
    Category,
    SecureItemInfo,
    ItemSecretIngredient,
    ItemSecret
)
from .forms import (
    SecureItemInfoForm_1,
    SecureItemInfoForm_2
)
from account.models import PassCode
from account.default import general_context
from toolkit import (
    check_user_passcode_set,
    passcode_required,
    InformationSecurity,
    MixinTrick
)


User = get_user_model()


@check_user_passcode_set(flash_for='item')
@passcode_required
def new_item(request):
    """First page for saving new item"""

    site_platform = Platform.objects.all()
    site_categories = Category.objects.all()
    
    # making list of platform, by using list comprehension. By default it will
    # return a tuples of (id, timestamp, platform_key, platform_value, category_id),
    # so we slice the fourth index `i[4]` which is the platform_value
    # l_platform = [i[4] for i in Platform.objects.values_list()]
    l_platform = [i['platform_value'] for i in Platform.objects.values_list().all().values()]
    
    # appending `custom`` in the `l_platform` list, because we did not added it directly into our database, to avoid being categorize into a category. Which will make us do alot if we add it there
    l_platform.append('custom')
    
    # making list of category, by using list comprehension. By default it will
    # return a tuples of (id, timestamp, category_key, category_value),
    # so we slice the third index `i[3]` which is the category_value
    # l_category = [i[3] for i in Category.objects.values_list()]
    l_category = [i['category_value'] for i in Category.objects.values_list().all().values()]
    
    # our default visibility list
    l_visibility = ['private', 'team', 'organisation']
    
    if request.method == 'POST':
        form = SecureItemInfoForm_1(request.POST)
        item_label = request.POST['i_label']

        # validating item label
        validate_label = SecureItemInfo.objects.filter(
            i_label=item_label, i_owner=request.user.passcode).first()
        if validate_label:
            flash_msg.warning(
                request, f'You already save an item with this label `{item_label}`')
            
        if form.is_valid():
            # Items values from html template
            item_category = form.cleaned_data.get("selected_category")
            item_platform = form.cleaned_data.get("selected_platform")
            item_custom_platform = form.cleaned_data.get("custom_platform")
            item_visibility = form.cleaned_data.get("visibility")
            
            context = {
                'item_category': item_category,
                'item_visibility': item_visibility,
                'item_platform': item_platform,
                'item_custom_platform': item_custom_platform,
                'item_label': item_label,
                
                'site_categories': site_categories,
                'site_platform': site_platform,
                'general_context': general_context(request),
            }
            
            # Checking for whether if a user edited the hidden fields by inspecting the page
            if item_visibility not in l_visibility:
                context = {
                    'form': form,
                    'site_categories': site_categories,
                    'site_platform': site_platform,
                    'l_platform': l_platform,
                    'l_category': l_category,
                    'general_context': general_context(request),
                }
                flash_msg.warning(
                    request, f'May be you edited your visibility field(s), thats why we redirect you back')
                return render(request, 'secureapp/new_item_1.html', context)
            
            if item_category not in l_category:
                context = {
                    'form': form,
                    'site_categories': site_categories,
                    'site_platform': site_platform,
                    'l_platform': l_platform,
                    'l_category': l_category,
                    'general_context': general_context(request),
                }
                flash_msg.warning(
                    request, f'May be you edited your category field(s), thats why we redirect you back')
                return render(request, 'secureapp/new_item_1.html', context)
            
            if item_platform not in l_platform:
                context = {
                    'form': form,
                    'site_categories': site_categories,
                    'site_platform': site_platform,
                    'l_platform': l_platform,
                    'l_category': l_category,
                    'general_context': general_context(request),
                }
                flash_msg.warning(
                    request, f'May be you edited your platform field(s), thats why we redirect you back')
                return render(request, 'secureapp/new_item_1.html', context)
            return render(request, 'secureapp/new_item_2.html', context)
    else:
        form = SecureItemInfoForm_1()

    context = {
        'form': form,
        'site_categories': site_categories,
        'site_platform': site_platform,
        'l_platform': l_platform,
        'l_category': l_category,
        'general_context': general_context(request),
    }
    return render(request, 'secureapp/new_item_1.html', context)


@check_user_passcode_set(flash_for='item')
@passcode_required
def new_item_fields(request):
    """Second page for saving new item"""

    the_i_owner = PassCode.objects.get(id=request.user.passcode.id)
    
    # making list of platform, by using list comprehension. By default it will
    # return a tuples of (id, timestamp, platform_key, platform_value, category_id),
    # so we slice the fourth index `i[4]` which is the platform_value
    # l_platform = [i[4] for i in Platform.objects.values_list()]
    l_platform = [i['platform_value'] for i in Platform.objects.values_list().all().values()]
    
    # appending `custom`` in the `l_platform` list, because we did not added it directly into our database, to avoid being categorize into a category. Which will make us do alot if we add it there
    l_platform.append('custom')
    
    # making list of category, by using list comprehension. By default it will
    # return a tuples of (id, timestamp, category_key, category_value),
    # so we slice the third index `i[3]` which is the category_value
    # l_category = [i[3] for i in Category.objects.values_list()]
    l_category = [i['category_value'] for i in Category.objects.values_list().all().values()]
    
    # our default visibility list
    l_visibility = ['private', 'team', 'organisation']
    
    if request.method == 'POST':
        form = SecureItemInfoForm_2(request.POST)

        if form.is_valid():
            # Items values from html template
            i_label = form.cleaned_data.get('i_label')
            i_category = form.cleaned_data.get("category")
            i_platform = form.cleaned_data.get("platform")
            i_custom_platform = form.cleaned_data.get("custom_platform")
            visibility = form.cleaned_data.get("visibility")
            
            # Checking for whether if a user edited the hidden fields by inspecting the page
            if visibility not in l_visibility:
                context = {
                    'form': form,
                    'general_context': general_context(request),
                }
                flash_msg.warning(
                    request, f'May be you edited your visibility field(s), thats why we redirect you back')
                return render(request, 'secureapp/new_item_1.html', context)
            
            if i_category not in l_category:
                context = {
                    'form': form,
                    'general_context': general_context(request),
                }
                flash_msg.warning(
                    request, f'May be you edited your category field(s), thats why we redirect you back')
                return render(request, 'secureapp/new_item_1.html', context)
            
            if i_platform not in l_platform:
                context = {
                    'form': form,
                    'general_context': general_context(request),
                }
                flash_msg.warning(
                    request, f'May be you edited your platform field(s), thats why we redirect you back')
                return render(request, 'secureapp/new_item_1.html', context)
            
            # fields for social
            i_username = form.cleaned_data.get('i_username')
            i_phone = form.cleaned_data['i_phone']
            i_email = form.cleaned_data['i_email']
            i_password = form.cleaned_data['i_password']
            
            # fields for cloud
            i_passphrase = form.cleaned_data['i_passphrase']
            i_api = form.cleaned_data['i_api']
            i_ssh_key_pub = form.cleaned_data['i_ssh_key_pub']
            i_ssh_key_prt = form.cleaned_data['i_ssh_key_prt']
            
            # fields for card
            i_card_no = form.cleaned_data['i_card_no']
            i_card_valid_range = form.cleaned_data['i_card_valid_range']
            i_card_ccv = form.cleaned_data['i_card_ccv']
            i_card_pin = form.cleaned_data['i_card_pin']
            
            # checking if all the fields are empty

templates/secureapp/add_trusted_user.html
{% extends 'base_1.html' %}
{% load static %}

{% block title %}
  add trusted user
{% endblock title %}


{% block main %}
  <div class="t_s">
    <p>Search trusted user</p>
    <form action="#">
      <a href="#">upgrade</a>
      <button type="submit">Edit</button>
    </form>
  </div>
  <div class="box">
  {% if searches %}
    {% for result in searches %}
      <div class="t_s">
        <p>Add trusted user <i>({{result.first_name}})</i></p>
      </div>

      <form action="{% url 'secureapp:add_trusted_user' item.id result.id %}" method="post" class="box">
        {% csrf_token %}
        <br>
        <div class="box_inn">
          <p>Trusted user full name:</p>
          <p class="box_border">
            <b>Full name: </b>
            {{result.first_name}} {{result.last_name}}
          </p>
          <br>
          <p>Trusted user other details:</p>
          <p class="box_border">
            <b>Username: </b>{{result.username}}
            <br>
            <b>Email: </b>{{result.email}}
            <br>
            <b>Phone number: </b>{{result.phone_number}}
          </p>
          <br>
          
          <p class="alert_warning">
            <input type="checkbox" required> Are you sure to add this trusted user?
            <a href="{% url 'secureapp:item_info' item.id %}" class="danger">No back to item</a>
          </p>
          <br>
          <div>
            <button type="submit">Add trusted user</button>
          </div>
          <br>
        </div>
      </form>
    {% endfor %}
  {% else %}
    <form method="get" action="" class="box_head">
      <small class="danger">Stay away from public when viewing information.</small>
      <small>Add a trusted user by searching his/her id or username</small>
      <br>
      <input type="search" name="search_trusted_user" placeholder="Search a trusted user">
      <button type="submit">search</button>
    </form>
    <br>
    <hr>
    <div class="box_center">
      <div class="box_border">
        <p class="alert_warning">We can't find trusted user with that data</p>
      </div>
    </div>
  {% endif %}
</div>
{% endblock main %}

templates/secureapp/base_2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'css/base_2.css' %}">
  {% block head %}
    <!-- content tags -->
  {% endblock head %}
  <title>PassAccess</title>
</head>
<body>
  <div class="container">

    <div class="header">
      <div class="head">
        <h1><a href="{% url 'secureapp:landing' %}">PassAccess</a></h1>
        <div class="div">
          {% if request.user.is_authenticated %}
            <a href="{% url 'secureapp:landing' %}" class="h_link">Dashboard</a>
            <a href="{% url 'auth:logout' %}" class="h_link">Logout</a>
            <a href="{% url 'secureapp:landing' %}" class="h_link_sm">Dashboard</a>
          {% else %}
            {% block link %}
              <!-- links -->
            {% endblock link %}
            <a href="#" class="h_link">About</a>
            <a href="#" class="h_link">Privacy</a>
          {% endif %}
        </div>
      </div>
    </div>

    <!-- flash messages -->
    {% if messages %}
      {% for flash_msg in messages %}
        <div class="alert_{{flash_msg.tags}}">
          <p class="alert_col_{{flash_msg.tags}}">{{flash_msg}}</p>
        </div>
      {% endfor %}
    {% endif %}
    
    {% block main %}
      <!-- main content -->
    {% endblock main %}

    <div class="form">
      {% block form %}
        <!-- form content -->
      {% endblock form %}
    </div>

    <div class="foot">
      <h1><a href="{% url 'secureapp:landing' %}">PassAccess</a></h1>
      <small><i>(Privacy is priority)</i></small>
      <!-- <small><i>Security is piority</i></small> -->
      <br>
      <br>
      <p>A password and sensitive information manager, that encrypt and save them for a user, which can be decrypt by the use when ever need to be. A security application that secure sensitive informations.</p>
      <br>
      {% if request.user.is_authenticated %}
        <li><a href="{% url 'secureapp:landing' %}">Dashboard</a></li>
        <li><a href="{% url 'auth:update_profile' %}">Update profile</a></li>
        <li><a href="{% url 'auth:change_password' %}">Change password</a></li>
        <li><a href="{% url 'auth:logout' %}">Logout</a></li>
      {% else %}
        &nbsp; <li><a href="{% url 'auth:login' %}">Login</a></li>
        &nbsp; <li><a href="{% url 'auth:signup' %}">Sign Up</a></li>
        &nbsp; <li><a href="#">About</a></li>
        &nbsp; <li><a href="#">Privacy</a></li>
      {% endif %}
      <br>
      <p>Alright reserved &copy; 2022 - {{the_year}}</p>
    </div>

  </div>
</body>
</html>

templates/secureapp/item_info.html
{% extends 'base_1.html' %}
{% load static %}

{% block title %}
  item info
{% endblock title %}


{% block main %}
  <div class="t_s">
    <p>&copy; {{item_unveil_info.platform}}</p>
    <form action="#">
      <a href="#">upgrade</a>
      <button type="submit">Edit</button>
    </form>
  </div>

  <div class="box">
    <form method="get" action="{% url 'secureapp:search_trusted_user' item_unveil_info.id %}" class="box_head">
      <small class="danger">Stay away from public when viewing information.</small>
      <small>Add a trusted user by searching his/her id or username</small>
      <br>
      <input type="search" name="search_trusted_user" placeholder="Search a trusted user">
      <button type="submit">search</button>
    </form>
    {% for result in searches %}
      <div class="trusted_user">
        <h4>{{result.first_name}} {{result.last_name}}</h4>
        <a href="#" class="peace">Add trusted user</a>
      </div>
    {% endfor %}
    <div class="trusted_user">
      <h4>Usman Musa</h4>
      <a href="#" class="peace">Add trusted user</a>
    </div>

    <div class="box_center">
      <div class="box_border">
        <p class="alert_warning">We can't find trusted user with that data</p>
      </div>
    </div>

    <div class="box_inn">
      <p>Label:</p>
      <p class="box_border">{{item_unveil_info.i_label}}</p>
      <br>
      <p>Visibility:</p>
      <p class="box_border">
        <a href="#" class="grey">{{item_unveil_info.visibility}} gist</a>
        <br>
        <b>Visibility: </b>{{item_unveil_info.visibility}} access
      </p>
      <br>
      <p>Category and platform</p>
      <p class="box_border">
        <b>Category:</b>
        {{item_unveil_info.category}}
        <br>
        <b>Platform:</b>
        {{item_unveil_info.platform}}

        <!-- handling custom platform view -->
        {% if item_unveil_info.custom_platform == None %}
          <!-- pass -->
        {% elif item_unveil_info.custom_platform == '' %}
          <!-- pass -->
        {% else %}
          <br>
          <b>Custom platform:</b>
          {{item_unveil_info.custom_platform}}
        {% endif %}
      </p>
      <br>


      <!-- for social media 
        we slice each item publick key from index 11 to end `<item_public_key>|slice:'12:'`
      -->
      <div class="box_border">
        <p>Your social media data will be visible here!</p>
        {% if item_unveil_info.i_username != None %}
          {% if item_unveil_info.i_username != "" %}
            <p>Username:</p>
            <span>
              <!-- <input type="password" name="" placeholder="Refresh the page to see username" value="{{item_unveil_info.i_username|slice:'12:'}}"> -->
              <input type="password" name="" placeholder="Refresh the page to see username" value="{{decrypt_i_username}}">
              <button type="button" onclick="show_sensitive_value(this)">Show</button>
            </span>
          {% endif %}
        {% endif %}

        {% if item_unveil_info.i_email != None %}
          {% if item_unveil_info.i_email != "" %}
            <p>Email:</p>
            <span>
              <!-- <input type="password" name="" placeholder="Refresh the page to see email" value="{{item_unveil_info.i_email|slice:'12:'}}"> -->
              <input type="password" name="" placeholder="Refresh the page to see username" value="{{decrypt_i_email}}">
              <button type="button" onclick="show_sensitive_value(this)">Show</button>
            </span>
          {% endif %}
        {% endif %}

        {% if item_unveil_info.i_password != None %}
          {% if item_unveil_info.i_password != "" %}
            <p>Password:</p>
            <span>
              <!-- <input type="password" name="" placeholder="Refresh the page to see password" value="{{item_unveil_info.i_password|slice:'12:'}}"> -->
              <input type="password" name="" placeholder="Refresh the page to see username" value="{{decrypt_i_password}}">
              <button type="button" onclick="show_sensitive_value(this)">Show</button>
            </span>
          {% endif %}
        {% endif %}
      </div>



      <!-- for card -->
      <br>
      <div class="box_border">
        <p>Your cards data will be visible here!</p>
        {% if item_unveil_info.i_card_no != None %}
          {% if item_unveil_info.i_card_no != "" %}
            <p>Card number:</p>
            <span>
              <!-- <input type="password" name="" placeholder="Refresh the page to see card number" value="{{item_unveil_info.i_card_no|slice:'12:'}}"> -->
              <input type="password" name="" placeholder="Refresh the page to see username" value="{{decrypt_i_card_no}}">
              <button type="button" onclick="show_sensitive_value(this)">Show</button>
            </span>
          {% endif %}
        {% endif %}

        {% if item_unveil_info.i_card_valid_range != None %}
          {% if item_unveil_info.i_card_valid_range != "" %}
            <p>Valid date:</p>
            <span>
              <!-- <input type="password" name="" placeholder="Refresh the page to see valid date" value="{{item_unveil_info.i_card_valid_range|slice:'12:'}}"> -->
              <input type="password" name="" placeholder="Refresh the page to see username" value="{{decrypt_i_card_valid_range}}">
              <button type="button" onclick="show_sensitive_value(this)">Show</button>
            </span>
            <br>
          {% endif %}
        {% endif %}

        {% if item_unveil_info.i_card_ccv != None %}
          {% if item_unveil_info.i_card_ccv != "" %}
            <p>cvv:</p>
            <span>
              <!-- <input type="password" name="" placeholder="Refresh the page to see ccv" value="{{item_unveil_info.i_card_ccv|slice:'12:'}}"> -->
              <input type="password" name="" placeholder="Refresh the page to see username" value="{{decrypt_i_card_ccv}}">
              <button type="button" onclick="show_sensitive_value(this)">Show</button>
            </span>
            <br>
          {% endif %}
        {% endif %}

        {% if item_unveil_info.i_card_pin != None %}
          {% if item_unveil_info.i_card_pin != "" %}
            <p>Pin:</p>
            <span>
              <!-- <input type="password" name="" placeholder="Refresh the page to see pin" value="{{item_unveil_info.i_card_pin|slice:'12:'}}"> -->
              <input type="password" name="" placeholder="Refresh the page to see username" value="{{decrypt_i_card_pin}}">
              <button type="button" onclick="show_sensitive_value(this)">Show</button>
            </span>
          {% endif %}
        {% endif %}
      </div>



      <!-- for cloud -->
      <br>
      <div class="box_border">
        <p>Your cloud data will be visible here!</p>
        {% if item_unveil_info.i_ssh_key_pub != None %}
          {% if item_unveil_info.i_ssh_key_pub != "" %}
            <p>ssh key public:</p>
            <span>
              <!-- <textarea name="" placeholder="Refresh the page to see ssh public key" cols="40" rows="5">{{item_unveil_info.i_ssh_key_pub|slice:'12:'}}</textarea> -->
              <input type="password" name="" placeholder="Refresh the page to see passphrase" value="{{decrypt_i_ssh_key_pub}}">
              <button type="button" onclick="show_sensitive_value(this)">Show</button>
            </span>
            <br>
            <br>
            <hr>
          {% endif %}
        {% endif %}

        {% if item_unveil_info.i_ssh_key_prt != None %}
          {% if item_unveil_info.i_ssh_key_prt != "" %}
            <p>ssh key private:</p>
            <span>
              <!-- <textarea name="" placeholder="Refresh the page to see ssh private key" cols="40" rows="5">{{item_unveil_info.i_ssh_key_prt|slice:'12:'}}</textarea> -->
              <input type="password" name="" placeholder="Refresh the page to see passphrase" value="{{decrypt_i_ssh_key_prt}}">
              <button type="button" onclick="show_sensitive_value(this)">Show</button>
            </span>
            <br>
            <br>
            <hr>
          {% endif %}
        {% endif %}

        {% if item_unveil_info.i_passphrase != None %}
          {% if item_unveil_info.i_passphrase != "" %}
            <p>Passphrase:</p>
            <span>
              <!-- <textarea name="" placeholder="Refresh the page to see passphrase" cols="40" rows="5">{{item_unveil_info.i_passphrase|slice:'12:'}}</textarea> -->
              <input type="password" name="" placeholder="Refresh the page to see passphrase" value="{{decrypt_i_passphrase}}">
              <button type="button" onclick="show_sensitive_value(this)">Show</button>
            </span>
            <br>
            <br>
            <hr>
          {% endif %}
        {% endif %}

        {% if item_unveil_info.i_api != None %}
          {% if item_unveil_info.i_api != "" %}
            <p>API token:</p>
            <small class="">The API might be for example github, twitter api and other platform api's</small>
            <br>
            <span>
              <!-- <textarea name="" placeholder="Refresh the page to see api token" cols="40" rows="5">{{item_unveil_info.i_api|slice:'12:'}}</textarea> -->
              <input type="password" name="" placeholder="Refresh the page to see passphrase" value="{{decrypt_i_api}}">
              <button type="button" onclick="show_sensitive_value(this)">Show</button>
            </span>
          {% endif %}
        {% endif %}
      </div>
      <br>


      <!-- history review -->
      <p class="box_border">
        <a href="#" class="grey">History logs</a>
        <br>
        <br>
        <b>Last review:</b> {{last_review}}
        <br>
        <b>Last modified:</b> {{item_unveil_info.date_modified|date:"d M, Y"}}
        <br>
        <b>Date created:</b> {{item_unveil_info.date_created|date:"d M, Y"}}
      </p>
      <br>
    </div>

    <div class="box_bot">
      <p>If you want to discard (delete) this item information click here <a href="{% url 'secureapp:delete_item' item_unveil_info.id %}" class="danger_round">Discard</a></p>
    </div>
  </div>

  <div class="box">
    <form method="get" action="{% url 'secureapp:search_trusted_user' item_unveil_info.id %}" class="box_head">
      <small class="danger">Stay away from public when viewing information.</small>
      <small>Add a trusted user by searching his/her id or username</small>
      <br>
      <input type="search" name="search_trusted_user" placeholder="Search a trusted user">
      <button type="submit">search</button>
    </form>
    <hr>
    {% if item_unveil_info.trusted_user.all.count > 0 %}
      <div class="box_head">
        <h1>Trusted users</h1>
        <small>These are your team (trusted user) that have access to this item</small>
      </div>
      {% for trust in item_unveil_info.trusted_user.all %}
        <div class="trusted_user">
          <h4>{{trust.first_name}} {{trust.last_name}}</h4>
          <a href="{% url 'secureapp:remove_trusted_user' item_unveil_info.id trust.id   %}" class="danger">Remove trusted user ({{trust.username}})</a>
        </div>
      {% endfor %}
    {% else %}
      <div class="box_center">
        <div class="box_border">
          <p class="alert_warning">No trusted added yet in this {{item_unveil_info.visibility}} item</p>
        </div>
      </div>
    {% endif %}

    <div class="box_bot">
      <p>You can remove all trusted user by just one click <a href="{% url 'secureapp:remove_all_trusted_user' item_unveil_info.id %}" class="danger_round">Remove all trusted user</a></p>
      <small>Note: removing trusted users may not give them access to this sensitive information</small>
    </div>
  </div>
{% endblock main %}