account/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .auth import (
    signup,
    validate_passcode,
    set_passcode,
    login_view,
    logout_view,
)
from .generate import (
    password_generator,
    generated_password,
    strong_password
)
from .update import (
    update_profile,
    change_password,
    update_passcode
)
from .views import (
    landing,
    dashboard,
    about,
    privacy,
    contact_us,
    help_page
)


app_name = 'auth'

urlpatterns = [
    # auth.py module path (views routes)
    path(
        'signup/', signup, name='signup'),
    path(
        'login/', login_view, name='login'),
    path(
        'validate/passcode/?next=/<str:next_url>/', validate_passcode, name='validate_passcode'),
    path(
        'logout/', logout_view, name='logout'),
    path(
        'set/passcode/', set_passcode, name='set_passcode'),
        

    # generator.py module path (views routes)
    path(
        'password/generator/', password_generator, name='password_generator'),
    path(
        'generated/password/', generated_password, name='generated_password'),
    path(
        'strong/password/<int:pwd_id>/', strong_password, name='strong_password'),
        

    # update.py module path (views routes)
    path(
        'update/profile/', update_profile, name='update_profile'),
    path(
        'change/password/', change_password, name='change_password'),
    path(
        'update/passcode/', update_passcode, name='update_passcode'),
        

    # views.py module path (views routes)
    path(
        '', landing, name='landing'),
    path(
        'dashboard/', dashboard, name='dashboard'),
    path(
        'about/', about, name='about'),
    path(
        'privacy/', privacy, name='privacy'),
    path(
        'contact/us/', contact_us, name='contact_us'),
    path(
        'help/', help_page, name='help'),
]

encme/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('secureapp.urls')),
]

passaccess/urls.py
from django.contrib import admin
from django.urls import path, include


# There are 4 already defined handler methods in `django.urls` functions.
handler400 = 'account.views.error_400'
handler403 = 'account.views.error_403'
handler404 = 'account.views.error_404'
handler500 = 'account.views.error_500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('secureapp.urls')),
]

secureapp/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .update import (
    update_item,
    update_item_salt
)
from .views import (
    new_item,
    new_item_fields,
    item_info,
    search_trusted_user,
    add_trusted_user,
    remove_trusted_user,
    remove_all_trusted_user,
    delete_item,
)


app_name = 'secureapp'

urlpatterns = [
    # views.py module path (views routes)
    path(
        'update/item/<int:item_id>/', update_item, name='update_item'),
    path(
        'update/item/salt/<int:item_id>/', update_item_salt, name='update_item_salt'),


    # views.py module path (views routes)
    path(
        'new/item/', new_item, name='new_item'),
    path(
        'new/item/fields', new_item_fields, name='new_item_fields'),
    path(
        'item/info/<int:item_id>/', item_info, name='item_info'),
    path(
        'search/trusted/<int:item_id>/', search_trusted_user, name='search_trusted_user'),
    path(
        'add/trusted/<int:item_id>/<int:user_id>/', add_trusted_user, name='add_trusted_user'),
    path(
        'remove/trusted/<int:item_id>/<int:user_id>/', remove_trusted_user, name='remove_trusted_user'),
    path(
        'remove/all/trusted/<int:item_id>/', remove_all_trusted_user, name='remove_all_trusted_user'),
    path(
        'delete/item/<int:item_id>/', delete_item, name='delete_item'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'base.css' %}">
  <script src="{% static 'js/base.js' %}"></script>
  <title>
    PassAccess | 
    {% block title %}
      <!-- inheritance -->
    {% endblock title %}
  </title>
</head>
<body onmouseover="loaddoc()">
  
  <!-- <script>
    function loaddoc(){
      var xhttp = new XMLHttpRequest();
      xhttp.onreadystatechange = function (){
        if (this.readyState == 4 && this.status == 200){
          // document.getElementById("com").innerHTML = this.getResponseHeader('content-length');
          document.querySelector('body').innerHTML = this.responseText;
        }
      };
      // xhttp.open("GET", "/dashboard", true);
      xhttp.send();
    }
  </script> -->

  <div class="container">
    <div class="nav_panel">
      <form class="search_form">
        <input type="search" name="" placeholder="Search here">
        <button type="submit">search</button>
        <img src="{% static 'img/hide_menu.png' %}" id="hide_menu_t" alt="" onclick="hideMenu()">
      </form>

      <div class="side">
        <div class="category">
          <h1>Category</h1>
          <p><a href="{% url 'secureapp:landing' %}">Dashboard</a></P>
            <p><a href="{% url 'secureapp:new_item' %}">New item</a></P>
            <p><a href="{% url 'secureapp:set_passcode' %}">Set secure</a></P>
            <p><a href="{% url 'secureapp:update_passcode' %}">Update secure</a></P>
          {% if request.user.passcode.passcode_ingredient == None or request.user.passcode.passcode_ingredient == '' %}
            <p><a href="{% url 'secureapp:set_passcode' %}">Finish setting passcode</a></P>
          {% endif %}
        </div>
        <br>

        {% block item %}
            <!-- items -->
        {% endblock item %}
        <br>
        <div class="category">
          <h1>Auth</h1>
          <p><a href="#">Secure Notes</a> <span>4</span></P>
          <p><a href="#">Trusted memberships</a><span>3</span></P>
          <p><a href="#">Trusted people</a><span>7</span></P>
          <p><a href="#">Contact Us</a></P>
          <p><a href="#">About</a></P>

          {% if request.user.is_authenticated %}
            <p><a href="admin">Admin</a></P>
            <p><a href="{% url 'auth:update_profile' %}">Update profile</a></P>
              <p><a href="{% url 'auth:password_generator' %}">Password generator</a></P>
                <p><a href="{% url 'auth:change_password' %}">Change password</a></P>
            <p><a href="{% url 'auth:logout' %}">Logout</a></P>
          {% else %}
            <p><a href="{% url 'auth:login' %}">Login</a></P>
            <p><a href="{% url 'auth:signup' %}">Sign Up</a></P>
          {% endif %}
        </div>
        <br>

        <div class="category">
          <h1>Trusted access</h1>
          <p><a href="#">Hamza Musa</a></P>
          <p><a href="#">Aliyu Samaila</a></P>
        </div>
        <br>

        <div class="foot">
          <small>Get 
            <a href="#">help</a> from PassAccess community or start live <a href="#">chat</a> with our people
          </small>
          <p>2022 - {{the_year}}</p>
        </div>
      </div>
    </div>

    <div class="main">
      <div class="header">
        <div class="l_header">
          <img src="{% static 'img/show_menu.png' %}" id="show_menu" alt="" onclick="showMenu()">
          <img src="{% static 'img/show_menu.png' %}" id="hide_menu" alt="" onclick="hideMenu()">
          <a href="{% url 'secureapp:landing' %}"><h1>PassAccess</h1></a>
        </div>

        <div class="r_header">
          <span>{{request.user.first_name|slice:':1'|upper}}{{request.user.last_name|slice:':1'|upper}}</span>
          <a href="#">{{request.user.first_name}} {{request.user.last_name}}</a>
          <a>|</a>
          <a href="#">Notification</a>
        </div>
      </div>

      <div class="main_inn">
        {% if messages %}
          {% for flash_msg in messages %}
            <div class="box">
              <div class="box_inn">
                <br>
                <div class="alert_{{flash_msg.tags}}">
                  <p class="alert_col_{{flash_msg.tags}}">{{flash_msg}}</p>
                </div>
                <br>
              </div>
            </div>
          {% endfor %}
        {% endif %}

        {% block main %}
          <!-- inheritance -->
        {% endblock main %}
      </div>
    </div>

  </div>
</body>
</html>

templates/base_1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'css/base_1.css' %}">
  <script src="{% static 'js/base.js' %}"></script>
  <title>
    PassAccess | {% block title %} <!-- title --> {% endblock title %}
  </title>
</head>
<body>
  {% if general_context.monitor_session_age == True and request.user.passcode.monitor_session_age == True %}
    <!-- these two span tags won`t be visible (they are hidden in the base_1.css file). The first one will count number of seconds of in active, while the second one is the logged in user session age value -->

    <!-- The ('monitor_session_age': True) within the default view's context dictionary (mostly in view that are decorated with `@passcode_required` and have page to render), enable the (security_secs, and security_user_sess_age) span tags to display in the html page. Note these two tags are only place at the top of this `base_1.html` where as some other pages are in herited from it(mostly those required passcode authentication). The javascript function for it is below the file, within the script (<script></script>) tag. All what am trying to say is, by the use of such, if a user take 30 seconds without doing nothing `(onload, onmousemove, onmousedown, ontouchstart, onclick, or onkeypress)` the screen page will be dim (dark navy in color).
    
    User can disable it by unchecking the checkbox in the update page. -->
    <span class="security_secs"></span>
    <span class="security_user_sess_age">{{request.user.passcode.session_age}}</span>
  {% endif %}
  {% include 'validator.html' %}
  
  <div class="container">
    <div class="nav_panel">
      <form class="search_form">
        <input type="search" name="" placeholder="Search here">
        <button type="submit">search</button>
        <img src="{% static 'img/hide_menu.png' %}" id="hide_menu_t" alt="" onclick="hide_menu()">
      </form>
      
      <div class="side">
        <div class="category">
          <h1>Dashboard</h1>
          <br>
          <p><a href="{% url 'auth:landing' %}">Overview</a></P>
          <p><a href="{% url 'secureapp:new_item' %}">New item</a></P>
          {% if request.user.passcode.passcode_ingredient == None or request.user.passcode.passcode_ingredient == '' %}
            <!-- pass -->
          {% else %}
            <br>
            <p><a>Number of items</a> <span>{{general_context.user_items.count}}</span></P>
            <p><a>Trusted users</a><span>{{general_context.t_users}}</span></P>
          {% endif %}
        </div>
        <br>
        
        {% block item %}
            <!-- items -->
        {% endblock item %}
        <div class="category">
          {% if request.user.passcode.passcode_ingredient == None or request.user.passcode.passcode_ingredient == '' %}
            <!-- pass -->
          {% else %}
            {% if general_context.user_items %}
              <h1>My items</h1>
              {% for item in general_context.user_items %}
                <p><a href="{% url 'secureapp:item_info' item.id %}">{{item.i_label}}</a></P>
              {% endfor %}
            {% endif %}
          {% endif %}
        </div>
        <br>

        <div class="category">
          <h1>Auth</h1>
          {% if request.user.passcode.passcode_ingredient == None or request.user.passcode.passcode_ingredient == '' %}
            <p><a href="{% url 'auth:set_passcode' %}">Set passcode</a></P>
          {% else %}
            <p><a href="{% url 'auth:update_profile' %}">Update profile</a></P>
            <p><a href="{% url 'auth:update_passcode' %}">Change passcode</a></P>
            <p><a href="{% url 'auth:change_password' %}">Change password</a></P>
            <p><a href="{% url 'auth:password_generator' %}">Generate password</a></P>
          {% endif %}
          {% if request.user.is_superuser == True %}
          <p><a href="/admin">Admin</a></P>
          {% endif %}
          <p><a href="{% url 'auth:logout' %}">Logout</a></P>
        </div>
        <br>
        
        <div class="category">
          <h1>Links</h1>
          <p><a href="{% url 'auth:help' %}">Help</a></P>
          <p><a href="{% url 'auth:about' %}">About</a></P>
          <p><a href="{% url 'auth:privacy' %}">Privacy</a></P>
          <p><a href="{% url 'auth:contact_us' %}">Contact Us</a></P>
          <p><a href="https://github.com/usmanmusa1920/pass-access">Repository</a></P>
        </div>
        <br>
        
        <div class="foot">
          <small>Get 
            <a href="{% url 'auth:help' %}">help</a> from PassAccess community or start live <a href="{% url 'auth:contact_us' %}">chat</a> with us via <a href="mailto:usmanmusa1920@gmail.com">email</a>.
          </small>
          <p>PassAcces &copy; 2022 - {{general_context.the_year}} <a href="https://usmanmusa1920.github.io">Designed & Developed</a></p>
        </div>
      </div>
    </div>
    
    <div class="main">
      <div class="header">
        <div class="l_header">
          <img src="{% static 'img/show_menu.png' %}" id="show_menu" alt="" onclick="show_menu()">
          <img src="{% static 'img/show_menu.png' %}" id="hide_menu" alt="" onclick="hide_menu()">
          <a href="{% url 'auth:landing' %}"><h1>PassAccess</h1></a>
        </div>
        
        <div class="r_header">
          <span>{{request.user.first_name|slice:':1'|upper}}{{request.user.last_name|slice:':1'|upper}}</span>
          <a href="{% url 'auth:landing' %}">{{request.user.first_name}} {{request.user.last_name}}</a>
          <a>|</a>
          <a href="{% url 'auth:logout' %}">Logout</a>
        </div>
      </div>
      
      <div class="main_inn">
        {% if messages %}
          {% for flash_msg in messages %}
            <div class="box">
              <div class="box_inn">
                <br>
                <div class="alert_{{flash_msg.tags}}">
                  <p class="alert_col_{{flash_msg.tags}}">{{flash_msg}}</p>
                </div>
                <br>
              </div>
            </div>
          {% endfor %}
        {% endif %}
        
        {% block main %}
          <!-- inheritance -->
        {% endblock main %}
      </div>
    </div>
    
  </div>
  <script type="text/javascript">
		let timer = 0;
		let currSeconds = 0;
    let secsCount = document.querySelector('.security_secs').textContent;
    let userSessionAge = document.querySelector('.security_user_sess_age').textContent;
    
		function resetTimer() {
			// Hide the timer text
			document.querySelector('body').style.display = 'block';
      document.querySelector('html').style.background = 'white';

			// Clear the previous interval
			clearInterval(timer);

			// Reset the seconds of the timer
			currSeconds = 0;

			// Set a new interval
      // NOTE: 1 second = 1000 milliseconds
			timer = setInterval(startIdleTimer, 1000);
		}
    
		// events that would reset the timer
		window.onload = resetTimer;
		window.onmousemove = resetTimer;
		window.onmousedown = resetTimer;
		window.ontouchstart = resetTimer;
		window.onclick = resetTimer;
		window.onkeypress = resetTimer;
    
		function startIdleTimer() {
			// Increment the timer seconds
			currSeconds++;

      // if (secsCount == userSessionAge / 2 || secsCount === userSessionAge / 2){
      if (secsCount == 30 || secsCount === 30){
        document.querySelector('body').style.display = 'none';
        document.querySelector('html').style.background = 'rgb(3, 3, 45)';
      }
      
			// Set the timer text to the new value
			secsCount = currSeconds;
		}
	</script>
</body>
</html>

templates/base_2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'css/base_2.css' %}">
  <script src="{% static 'js/base.js' %}"></script>
  {% block head %} <!-- head --> {% endblock head %}
  <title>PassAccess | {% block title %} <!-- title --> {% endblock title %}</title>
</head>
<body>
  {% include 'validator.html' %}
  <div class="container">

    <div class="header">
      <div class="head">
        <h1><a href="{% url 'auth:landing' %}">PassAccess</a></h1>
        <div class="div">
          {% if request.user.is_authenticated %}
            <a href="{% url 'auth:logout' %}" class="h_link">Logout</a>
            <a href="{% url 'auth:logout' %}" class="h_link_sm">Logout</a>
          {% else %}
            {% block link %}
              <!-- links -->
            {% endblock link %}
            <a href="{% url 'auth:about' %}" class="h_link">About</a>
            <a href="{% url 'auth:privacy' %}" class="h_link">Privacy</a>
          {% endif %}
        </div>
      </div>
    </div>

    <!-- flash messages -->
    {% if messages %}
      {% for flash_msg in messages %}
        <div class="alert_{{flash_msg.tags}}">
          <p class="alert_col_{{flash_msg.tags}}">{{flash_msg}}</p>
        </div>
      {% endfor %}
    {% endif %}
    
    {% block main %}
      <!-- main content -->
    {% endblock main %}

    <div class="form">
      {% block form %}
        <!-- form content -->
      {% endblock form %}
    </div>

    <div class="foot">
      <h1><a href="{% url 'auth:landing' %}">PassAccess</a></h1>
      <small><i>(Security & privacy is priority)</i></small>
      <br>
      <br>
      <p>A password and sensitive information manager, that encrypt and save them for a user, which can be decrypt by the use when ever need to be. A security application that secure sensitive informations.</p>
      <br>
      {% if request.user.is_authenticated %}
        <li><a href="{% url 'auth:landing' %}">Dashboard</a></li>
        <li><a href="{% url 'auth:logout' %}">Logout</a></li>
      {% else %}
        <li><a href="{% url 'auth:login' %}">Login</a></li>
        <li><a href="{% url 'auth:signup' %}">Sign Up</a></li>
      {% endif %}
      <li><a href="{% url 'auth:about' %}">About</a></li>
      <li><a href="{% url 'auth:privacy' %}">Privacy</a></li>
      <li><a href="{% url 'auth:help' %}">Help</a></li>
      <li><a href="{% url 'auth:contact_us' %}">Contact Us</a></li>
      <br>
      <p>Alright reserved PassAcces &copy; 2022 - {{general_context.the_year}} <a href="https://usmanmusa1920.github.io">Designed & Developed</a></p>
    </div>
  </div>
</body>
</html>

templates/validator.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/validator.css' %}">

<!-- 
  This include file is for pages that will restrict user from clicking anywhere when submitting a request (while processing)
-->

<div class="dew">
  <span class="dew_span">
    <div class="dew_authentic">
      <div class="dew_cntr">
        <div class="dew_circle"></div>
        <small class="dew_scan"></small>
        <div class="dew_pointer_cntr">
          <span class="dew_pointer">
            <span class="period"></span>
          </span>
        </div>
        <div class="dew_gradient_circle"></div>
      </div>
    </div>
  </span>
</div>